"""initial dizal schema

Revision ID: 89f47e4e0629
Revises: 
Create Date: 2026-09-28 01:56:08.370601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f47e4e0629'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_code'), ['code'], unique=True)

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_permission_module'), ['module'], unique=False)

    op.create_table('project_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'year', name='uq_sequence_type_year')
    )
    op.create_table('project_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('singleton_key', sa.String(length=20), nullable=False),
    sa.Column('project_name', sa.String(length=150), nullable=False),
    sa.Column('manager_name', sa.String(length=150), nullable=True),
    sa.Column('manager_phone', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('drum_liters', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('max_farmers_per_employee', sa.Integer(), nullable=False),
    sa.Column('max_credit_drums_per_farmer', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('max_dispense_liters_per_day', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('default_sale_price_per_liter', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('minimum_stock_liters', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=False),
    sa.Column('accent_color', sa.String(length=20), nullable=False),
    sa.Column('surface_color', sa.String(length=20), nullable=False),
    sa.Column('danger_color', sa.String(length=20), nullable=False),
    sa.Column('radius', sa.String(length=20), nullable=False),
    sa.Column('font_family', sa.String(length=80), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('manager_signature_path', sa.String(length=500), nullable=True),
    sa.Column('document_header', sa.Text(), nullable=True),
    sa.Column('document_footer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_key')
    )
    op.create_table('role',
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', flask_security.datastore.AsaList(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('is_employee', sa.Boolean(), nullable=False),
    sa.Column('us_totp_secrets', sa.Text(), nullable=True),
    sa.Column('us_phone_number', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('current_login_ip', sa.String(length=64), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('tf_primary_method', sa.String(length=64), nullable=True),
    sa.Column('tf_totp_secret', sa.String(length=255), nullable=True),
    sa.Column('tf_phone_number', sa.String(length=128), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('whatsapp_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_token', sa.String(length=1000), nullable=True),
    sa.Column('sender_number', sa.String(length=50), nullable=True),
    sa.Column('webhook_secret', sa.String(length=200), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=True),
    sa.Column('object_id', sa.String(length=80), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_request_id'), ['request_id'], unique=False)

    op.create_table('cashbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('box_type', sa.String(length=30), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashbox_box_type'), ['box_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashbox_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_document_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_source_type'), ['source_type'], unique=False)

    op.create_table('employee_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('salary_type', sa.String(length=30), nullable=False),
    sa.Column('salary_value', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('farmer_limit_override', sa.Integer(), nullable=True),
    sa.Column('credit_limit_override', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('daily_liters_limit_override', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('can_change_farmer_quota', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('farmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quota_drums', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('credit_limit_drums', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('assigned_employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_assigned_employee_id'), ['assigned_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_farmer_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_status'), ['status'], unique=False)

    op.create_table('fuel_tank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('capacity_liters', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('custodian_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['custodian_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_tank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_tank_code'), ['code'], unique=True)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.Column('whatsapp', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_permission_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=120), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_permission_override', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_permission_override_permission_key'), ['permission_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_override_user_id'), ['user_id'], unique=False)

    op.create_table('whatsapp_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=40), nullable=False),
    sa.Column('template_key', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('attachment_storage_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('provider_message_id', sa.String(length=160), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_message_recipient'), ['recipient'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_message_status'), ['status'], unique=False)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('payer_cashbox_id', sa.Integer(), nullable=False),
    sa.Column('custodian_user_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['custodian_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['payer_cashbox_id'], ['cashbox.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset_code'), ['asset_code'], unique=True)

    op.create_table('capital_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('source_cashbox_id', sa.Integer(), nullable=False),
    sa.Column('destination_cashbox_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['destination_cashbox_id'], ['cashbox.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_cashbox_id'], ['cashbox.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capital_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capital_allocation_employee_id'), ['employee_id'], unique=False)

    op.create_table('capital_contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('source', sa.String(length=180), nullable=True),
    sa.Column('cashbox_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashbox.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashbox_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=60), nullable=True),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashbox.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashbox_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashbox_transaction_cashbox_id'), ['cashbox_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashbox_transaction_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashbox_transaction_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('document_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=250), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_attachment_document_id'), ['document_id'], unique=False)

    op.create_table('employee_settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('actual_cash', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('cash_shortage', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('cash_overage', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('sales_amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('cost_of_sales', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('operating_expenses', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('employee_salary', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('owner_transfer', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('retained_operating_capital', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('employee_settlement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_settlement_employee_id'), ['employee_id'], unique=False)

    op.create_table('farmer_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('original_name', sa.String(length=250), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_document_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_document_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('farmer_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('farmer_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_payment_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_payment_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('farmer_quota_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('old_quota_drums', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('new_quota_drums', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('old_credit_limit_drums', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('new_credit_limit_drums', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_quota_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_quota_movement_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('fuel_dispense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('drums', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('sale_price_per_liter', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('credit_drums', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['fuel_tank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('fuel_dispense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_dispense_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_dispense_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_dispense_tank_id'), ['tank_id'], unique=False)

    op.create_table('fuel_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('supplier_name', sa.String(length=180), nullable=True),
    sa.Column('liters', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('diesel_amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('other_fee', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('landed_cost', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['fuel_tank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_purchase_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_purchase_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_purchase_tank_id'), ['tank_id'], unique=False)

    op.create_table('fuel_stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('liters', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['fuel_tank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_stock_movement_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_stock_movement_tank_id'), ['tank_id'], unique=False)

    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_source_type'), ['source_type'], unique=False)

    op.create_table('operating_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('cashbox_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashbox.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('operating_expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operating_expense_employee_id'), ['employee_id'], unique=False)

    op.create_table('farmer_payment_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('dispense_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('drums', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['dispense_id'], ['fuel_dispense.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['farmer_payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_payment_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_payment_allocation_dispense_id'), ['dispense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_payment_allocation_payment_id'), ['payment_id'], unique=False)

    op.create_table('fuel_stock_layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('original_liters', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('remaining_liters', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['fuel_purchase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tank_id'], ['fuel_tank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_stock_layer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_stock_layer_purchase_id'), ['purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_stock_layer_tank_id'), ['tank_id'], unique=False)

    op.create_table('journal_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_line_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_journal_entry_id'), ['journal_entry_id'], unique=False)

    op.create_table('fuel_stock_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispense_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispense_id'], ['fuel_dispense.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['layer_id'], ['fuel_stock_layer.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_stock_consumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_stock_consumption_dispense_id'), ['dispense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_stock_consumption_layer_id'), ['layer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_stock_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_stock_consumption_layer_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_stock_consumption_dispense_id'))

    op.drop_table('fuel_stock_consumption')
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_line_journal_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_employee_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_account_id'))

    op.drop_table('journal_line')
    with op.batch_alter_table('fuel_stock_layer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_stock_layer_tank_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_stock_layer_purchase_id'))

    op.drop_table('fuel_stock_layer')
    with op.batch_alter_table('farmer_payment_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_payment_allocation_payment_id'))
        batch_op.drop_index(batch_op.f('ix_farmer_payment_allocation_dispense_id'))

    op.drop_table('farmer_payment_allocation')
    with op.batch_alter_table('operating_expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operating_expense_employee_id'))

    op.drop_table('operating_expense')
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_source_type'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_source_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_entry_date'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_document_id'))

    op.drop_table('journal_entry')
    with op.batch_alter_table('fuel_stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_stock_movement_tank_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_stock_movement_movement_type'))

    op.drop_table('fuel_stock_movement')
    with op.batch_alter_table('fuel_purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_purchase_tank_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_purchase_status'))
        batch_op.drop_index(batch_op.f('ix_fuel_purchase_employee_id'))

    op.drop_table('fuel_purchase')
    with op.batch_alter_table('fuel_dispense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_dispense_tank_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_dispense_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_dispense_employee_id'))

    op.drop_table('fuel_dispense')
    with op.batch_alter_table('farmer_quota_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_quota_movement_farmer_id'))

    op.drop_table('farmer_quota_movement')
    with op.batch_alter_table('farmer_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_payment_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_farmer_payment_employee_id'))

    op.drop_table('farmer_payment')
    with op.batch_alter_table('farmer_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_document_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_farmer_document_document_type'))

    op.drop_table('farmer_document')
    with op.batch_alter_table('employee_settlement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_settlement_employee_id'))

    op.drop_table('employee_settlement')
    with op.batch_alter_table('document_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_attachment_document_id'))

    op.drop_table('document_attachment')
    with op.batch_alter_table('cashbox_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashbox_transaction_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_cashbox_transaction_document_id'))
        batch_op.drop_index(batch_op.f('ix_cashbox_transaction_cashbox_id'))

    op.drop_table('cashbox_transaction')
    op.drop_table('capital_contribution')
    with op.batch_alter_table('capital_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capital_allocation_employee_id'))

    op.drop_table('capital_allocation')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_asset_code'))

    op.drop_table('asset')
    with op.batch_alter_table('whatsapp_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_message_status'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_message_recipient'))

    op.drop_table('whatsapp_message')
    with op.batch_alter_table('user_permission_override', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permission_override_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_permission_override_permission_key'))

    op.drop_table('user_permission_override')
    op.drop_table('roles_users')
    op.drop_table('role_permission')
    op.drop_table('notification_preference')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('fuel_tank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_tank_code'))

    op.drop_table('fuel_tank')
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_status'))
        batch_op.drop_index(batch_op.f('ix_farmer_phone'))
        batch_op.drop_index(batch_op.f('ix_farmer_name'))
        batch_op.drop_index(batch_op.f('ix_farmer_code'))
        batch_op.drop_index(batch_op.f('ix_farmer_assigned_employee_id'))

    op.drop_table('farmer')
    op.drop_table('employee_profile')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_source_type'))
        batch_op.drop_index(batch_op.f('ix_document_source_id'))
        batch_op.drop_index(batch_op.f('ix_document_number'))
        batch_op.drop_index(batch_op.f('ix_document_document_type'))

    op.drop_table('document')
    with op.batch_alter_table('cashbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashbox_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_cashbox_box_type'))

    op.drop_table('cashbox')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_object_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_object_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    op.drop_table('whatsapp_template')
    op.drop_table('whatsapp_config')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))

    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('project_settings')
    op.drop_table('project_sequence')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_module'))
        batch_op.drop_index(batch_op.f('ix_permission_key'))

    op.drop_table('permission')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_code'))
        batch_op.drop_index(batch_op.f('ix_account_account_type'))

    op.drop_table('account')
    # ### end Alembic commands ###
